spring.application.name=backend

# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=jdbc:postgresql://ep-jolly-wildflower-b397skq1-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RKfz4mh1FpOV
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Flyway Database Migration
# ===============================

spring.flyway.enabled=true


# ===============================
# Server
# ===============================

server.port=8080

jwt.secret=YOUR_LONG_RANDOM_SECRET_KEY_HERE
jwt.expiration=86400000
hi