spring.application.name=backend

# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Flyway Database Migration
# ===============================

spring.flyway.enabled=true


# ===============================
# Server
# ===============================

server.port=${PORT:8080}


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


springdoc.api-docs.path=${OPENAPI_PATH}
springdoc.swagger-ui.path=${SWAGGAR_URL}

# ===============================
# Cloudinary Storage
# ===============================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

storage.path=${STORAGE_PATH}

# ===============================
# RabbitMQ
# ===============================

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}

#ai-resume-parser-url

ai.parser.base-url=${AI_PARSER_BASE_URL}